name: Continious Integration
on: push
jobs:
  run_code_checks:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          sudo mysql -e 'CREATE DATABASE ${{DB_NAME}};' -uroot -proot
      - name: Checkout Repo Code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version:1.23
      - name: Run linting
        run: |
          go fmt ./...
          go vet ./...
      - name: Run tests
        run: go test

